### ISSUE TITLE
How install on redbot ?

### ISSUE THREAD

**Issue by gamersalpha** [Sebass13/Sebass-Cogs#1]
Hello there, 

i have a frech install server with ark and redbot, how instlal u cog please and using it please ?

**Comment by gamersalpha** [comment]
First respons to install on u own redbot server do in channel discord : 


`arkserver-botcog repo add Sebass-Cogs https://github.com/Sebass13/Sebass-Cogs`
and type : 
`I agree`

and load the repo : 

`arkserver-botcog install Sebass-Cogs rcon`

after this installation is OK !!

but now how make interaction with arkserver please ?

**Comment by gamersalpha** [comment]
Looks like command like this : 

Add u serveur  : 

`arkserver-botserver add ark.serveur.com password arkserveur`

list serveur added in bot : 

`arkserver-botserver list`

Connect on the serveur  👍 

`arkserver-botserver  connect arkserver`

**Comment by gamersalpha** [comment]
Bot not working for me i have this error : 

Adding serveur : 

`arkserver-botserver add ark.serveur.com password arkserveur`

```
Arkserver-BotBOT - Aujourd'hui à 20:40
arkserver-botserver add <address> <password> <name> [multiple_packet=True] [timeout]

Adds and names a server's RCON.

Use this command in a direct message to keep your password secret.
Disable multiple packet responses only if you know what you're doing.

```

when i try to list : 

`arkserver-botserver list`

```

Arkserver-BotBOT - Aujourd'hui à 20:39
Error in command 'server list'. Check your console or logs for details.
```
and log in command line : 
```
Copying rcon...
[23/07/2018 18:35] ERROR red on_command_error 369: Exception in command 'server list'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/redbot/Red-DiscordBot/cogs/rcon.py", line 237, in list
    longest = max(len(name) for name in self.json)
ValueError: max() arg is an empty sequence
[23/07/2018 18:35] ERROR red on_command_error 369: Exception in command 'server list'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/redbot/Red-DiscordBot/cogs/rcon.py", line 237, in list
    longest = max(len(name) for name in self.json)
ValueError: max() arg is an empty sequence
```
and when i try to connect : 

`arkserver-botserver connect arkserver`
```



Arkserver-BotBOT - Aujourd'hui à 20:45
There are no servers named arkserver, check arkserver-botserver list for all servers.
```
